Travis-ci: Force use of last known working nightly toolchain for clippy
Travis-ci builds fail at the installation of Clippy after emptying build caches,
complaining that Clippy is unavailable for the nightly channel:

  $ rustup component add clippy

  error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable
  for download for channel 'nightly'

  If you require these components, please install and use the latest successful
  build version, which you can find at
  https://rust-lang-nursery.github.io/rust-toolstate.

  After determining the correct date, install it with a command such as:

    rustup toolchain install nightly-2018-12-27

  Then you can use the toolchain with commands such as:

    cargo +nightly-2018-12-27 build

  The command "rustup component add clippy" failed and exited with 1 during .

This patch forces installation of clippy from from nightly-2019-07-19, which is
the latest known working version according to [1] at the moment of this commit .

[1] https://rust-lang.github.io/rustup-components-history/index.html